### PR TITLE
Add support for sampling

### PR DESCRIPTION
**Pull request by dvic**

### CODE REVIEW

**Comment by dvic** [comment]
I'll probably change the option to just be `sampler` (no function) as I've opened a PR https://github.com/open-telemetry/opentelemetry-erlang/pull/260 that enables properly creating custom samplers (where the filtering can be done inside of those custom samplers).

**Comment by dvic** [comment]
As in https://github.com/opentelemetry-beam/opentelemetry_ecto/pull/17, the type for the sampler option is now actually 

```elixir
:otel_sampler.t() | sampler_fun() | nil
```

with 
```elixir
  @type sampler_fun :: (telemetry_data() -> :otel_sampler.t() | nil)
  @type telemetry_data :: %{measurements: map(), meta: map()}
```

The reason for still having the option to use a function is that you might want to return a built-in sampler for certain requests (e.g., the `TraceIdRatioBased` sampler) so that the application monitoring systems (APM) can correctly calculate statistics based of this information. If there is always one custom sampler, an APM can't know which request was sampled and which one was not.

The tests include an example that creates a custom sampler and mentions open-telemetry/opentelemetry-erlang#260.

**Comment by dvic** [comment]
@bryannaegele there seems to be an issue with the dialyzer ci setup but I've merged main into this branch. Let me know if there's anything else you would like to see changed in this PR.

**Comment by bryannaegele** [comment]
Archiving this repo since the move is complete. Can you open a new PR in the new repo? https://github.com/open-telemetry/opentelemetry-erlang-contrib and link to this one

Sorry for any inconvenience

**Pull request closed without merging**
