### PR TITLE
v1.0.0-rc.1

### PR DESCRIPTION
**Pull request by bryannaegele**
Update Otel support to v1.0.0-rc line. With the updates to Otel context handling, use OpentelemetryTelemetry beta to manage contexts properly.

### CODE REVIEW

**Comment by ricardoccpaiva** [comment]
Hi @bryannaegele :wave: 
is this going to be merged soon?

**Comment by bryannaegele** [comment]
@ricardoccpaiva I'm going to merge it but it would be great if some folks could reference that commit and test it out before I cut a release.

**Comment by bryannaegele** [comment]
@tsloughter any comments on this implementation?

**Review by tsloughter — APPROVED** [review]

**Comment by ricardoccpaiva** [comment]
> @ricardoccpaiva I'm going to merge it but it would be great if some folks could reference that commit and test it out before I cut a release.

I can do that @bryannaegele, any specific tests that you recommend?

**Comment by bryannaegele** [comment]
> > @ricardoccpaiva I'm going to merge it but it would be great if some folks could reference that commit and test it out before I cut a release.
> 
> I can do that @bryannaegele, any specific tests that you recommend?

Just check around and see if you're missing any telemetry-based spans and nothing looks off. I'd throw it into one of our apps but we haven't had a chance to get on 1.0-rc yet.

**Comment by ricardoccpaiva** [comment]
> > > @ricardoccpaiva I'm going to merge it but it would be great if some folks could reference that commit and test it out before I cut a release.
> > 
> > 
> > I can do that @bryannaegele, any specific tests that you recommend?
> 
> Just check around and see if you're missing any telemetry-based spans and nothing looks off. I'd throw it into one of our apps but we haven't had a chance to get on 1.0-rc yet.

Hi @bryannaegele , I think there may be something wrong :point_down: 
image

`unknown_service_erl` ---> v1.0rc
`unknown` ---> v0.6

Look at the transaction types, they are different :thinking: Detail of the transaction is also very different 
v0.6 :point_down:


image


v1.0rc :point_down: 


image

**Comment by bryannaegele** [comment]
OK. I'll try to do some testing this week. The first thing - `unknown` vs `unknown_service_erl` is probably an expected change just from 1.0. 

Can you confirm there weren't any errors in your logs?

**Comment by ricardoccpaiva** [comment]
> OK. I'll try to do some testing this week. The first thing - `unknown` vs `unknown_service_erl` is probably an expected change just from 1.0.
> 
> Can you confirm there weren't any errors in your logs?

I'll try to do that later today.

**Comment by ricardoccpaiva** [comment]
> > OK. I'll try to do some testing this week. The first thing - `unknown` vs `unknown_service_erl` is probably an expected change just from 1.0.
> > Can you confirm there weren't any errors in your logs?
> 
> I'll try to do that later today.


there are a few warnings :point_down: 

`````
==> Compiling opentelemetry_exporter
==> opentelemetry_telemetry
Compiling 1 file (.erl)
Compiling 1 file (.ex)
Generated opentelemetry_telemetry app
==> opentelemetry_phoenix
Compiling 2 files (.ex)
warning: Plug.Conn.get_peer_data/1 is undefined (module Plug.Conn is not available or is yet to be defined)
  lib/opentelemetry_phoenix.ex:107: OpentelemetryPhoenix.handle_endpoint_start/4

warning: Plug.Conn.get_req_header/2 is undefined (module Plug.Conn is not available or is yet to be defined)
Found at 2 locations:
  lib/opentelemetry_phoenix.ex:191: OpentelemetryPhoenix.client_ip/1
  lib/opentelemetry_phoenix.ex:201: OpentelemetryPhoenix.header_value/2

warning: OpentelemetryTelemetry.end_telemetry_span/2 is undefined or private
  lib/opentelemetry_phoenix.ex:139: OpentelemetryPhoenix.handle_endpoint_stop/4

warning: OpentelemetryTelemetry.set_current_telemetry_span/2 is undefined or private
Found at 3 locations:
  lib/opentelemetry_phoenix.ex:135: OpentelemetryPhoenix.handle_endpoint_stop/4
  lib/opentelemetry_phoenix.ex:150: OpentelemetryPhoenix.handle_router_dispatch_start/4
  lib/opentelemetry_phoenix.ex:162: OpentelemetryPhoenix.handle_router_dispatch_exception/4

warning: OpentelemetryTelemetry.start_telemetry_span/4 is undefined or private
  lib/opentelemetry_phoenix.ex:128: OpentelemetryPhoenix.handle_endpoint_start/4

Generated opentelemetry_phoenix app

**Comment by ricardoccpaiva** [comment]
and a few errors just by doing a single request :point_down: 

```` 
info] GET /api/users
[error] Handler {OpentelemetryPhoenix, :endpoint_start} has failed and has been detached. Class=:error
Reason=:undef
Stacktrace=[
  {OpentelemetryTelemetry, :start_telemetry_span,
   [
     :opentelemetry_phoenix,
     "HTTP GET",
     %{
       conn: %Plug.Conn{
         adapter: {Plug.Cowboy.Conn, :...},
         assigns: %{},
         before_send: [],
         body_params: %Plug.Conn.Unfetched{aspect: :body_params},
         cookies: %{},
         halted: false,
         host: "localhost",
         method: "GET",
         owner: #PID<0.523.0>,
         params: %{},
         path_info: ["api", "users"],
         path_params: %{},
         port: 4000,
         private: %{
           phoenix_endpoint: MyTelemetryApiWeb.Endpoint,
           phoenix_request_logger: {"request_logger", "request_logger"}
         },
         query_params: %{},
         query_string: "",
         remote_ip: {127, 0, 0, 1},
         req_cookies: %{},
         req_headers: [
           {"accept", "*/*"},
           {"host", "localhost:4000"},
           {"user-agent", "curl/7.68.0"}
         ],
         request_path: "/api/users",
         resp_body: nil,
         resp_cookies: %{},
         resp_headers: [
           {"cache-control", "max-age=0, private, must-revalidate"},
           {"x-request-id", "FnfT5pqxgPFA0UMAAANj"}
         ],
         scheme: :http,
         script_name: [],
         secret_key_base: :...,
         state: :unset,
         status: nil
       },
       options: []
     },
     %{kind: :server}
   ], []},
  {OpentelemetryPhoenix, :handle_endpoint_start, 4,
   [file: 'lib/opentelemetry_phoenix.ex', line: 128]},
  {:telemetry, :"-execute/3-fun-0-", 4,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/telemetry/src/telemetry.erl',
     line: 135
   ]},
  {:lists, :foreach, 2, [file: 'lists.erl', line: 1342]},
  {Plug.Telemetry, :call, 2, [file: 'lib/plug/telemetry.ex', line: 72]},
  {MyTelemetryApiWeb.Endpoint, :plug_builder_call, 2,
   [file: 'lib/my_telemetry_api_web/endpoint.ex', line: 1]},
  {MyTelemetryApiWeb.Endpoint, :"call (overridable 3)", 2,
   [file: 'lib/plug/debugger.ex', line: 132]},
  {MyTelemetryApiWeb.Endpoint, :call, 2,
   [file: 'lib/my_telemetry_api_web/endpoint.ex', line: 1]},
  {Phoenix.Endpoint.Cowboy2Handler, :init, 4,
   [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 65]},
  {:cowboy_handler, :execute, 2,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/cowboy/src/cowboy_handler.erl',
     line: 37
   ]},
  {:cowboy_stream_h, :execute, 3,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/cowboy/src/cowboy_stream_h.erl',
     line: 300
   ]},
  {:cowboy_stream_h, :request_process, 3,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/cowboy/src/cowboy_stream_h.erl',
     line: 291
   ]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
]

[debug] Processing with MyTelemetryApiWeb.UserController.index/2
  Parameters: %{}
  Pipelines: [:api]
[error] Handler {OpentelemetryPhoenix, :router_dispatch_start} has failed and has been detached. Class=:error
Reason=:undef
Stacktrace=[
  {OpentelemetryTelemetry, :set_current_telemetry_span,
   [
     :opentelemetry_phoenix,
     %{
       conn: %Plug.Conn{
         adapter: {Plug.Cowboy.Conn, :...},
         assigns: %{},
         before_send: [#Function<0.11227428/1 in Plug.Telemetry.call/2>],
         body_params: %{},
         cookies: %{},
         halted: false,
         host: "localhost",
         method: "GET",
         owner: #PID<0.523.0>,
         params: %{},
         path_info: ["api", "users"],
         path_params: %{},
         port: 4000,
         private: %{
           MyTelemetryApiWeb.Router => {[], %{}},
           :phoenix_endpoint => MyTelemetryApiWeb.Endpoint,
           :phoenix_request_logger => {"request_logger", "request_logger"},
           :phoenix_router => MyTelemetryApiWeb.Router,
           :plug_session_fetch => #Function<1.123471702/1 in Plug.Session.fetch_session/1>
         },
         query_params: %{},
         query_string: "",
         remote_ip: {127, 0, 0, 1},
         req_cookies: %{},
         req_headers: [
           {"accept", "*/*"},
           {"host", "localhost:4000"},
           {"user-agent", "curl/7.68.0"}
         ],
         request_path: "/api/users",
         resp_body: nil,
         resp_cookies: %{},
         resp_headers: [
           {"cache-control", "max-age=0, private, must-revalidate"},
           {"x-request-id", "FnfT5pqxgPFA0UMAAANj"}
         ],
         scheme: :http,
         script_name: [],
         secret_key_base: :...,
         state: :unset,
         status: nil
       },
       log: :debug,
       path_params: %{},
       pipe_through: [:api],
       plug: MyTelemetryApiWeb.UserController,
       plug_opts: :index,
       route: "/api/users"
     }
   ], []},
  {OpentelemetryPhoenix, :handle_router_dispatch_start, 4,
   [file: 'lib/opentelemetry_phoenix.ex', line: 150]},
  {:telemetry, :"-execute/3-fun-0-", 4,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/telemetry/src/telemetry.erl',
     line: 135
   ]},
  {:lists, :foreach, 2, [file: 'lists.erl', line: 1342]},
  {Phoenix.Router, :__call__, 2, [file: 'lib/phoenix/router.ex', line: 345]},
  {MyTelemetryApiWeb.Endpoint, :plug_builder_call, 2,
   [file: 'lib/my_telemetry_api_web/endpoint.ex', line: 1]},
  {MyTelemetryApiWeb.Endpoint, :"call (overridable 3)", 2,
   [file: 'lib/plug/debugger.ex', line: 132]},
  {MyTelemetryApiWeb.Endpoint, :call, 2,
   [file: 'lib/my_telemetry_api_web/endpoint.ex', line: 1]},
  {Phoenix.Endpoint.Cowboy2Handler, :init, 4,
   [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 65]},
  {:cowboy_handler, :execute, 2,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/cowboy/src/cowboy_handler.erl',
     line: 37
   ]},
  {:cowboy_stream_h, :execute, 3,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/cowboy/src/cowboy_stream_h.erl',
     line: 300
   ]},
  {:cowboy_stream_h, :request_process, 3,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/cowboy/src/cowboy_stream_h.erl',
     line: 291
   ]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
]

[debug] QUERY OK source="users" db=0.4ms queue=0.5ms idle=183.4ms
SELECT u0."id", u0."age", u0."name", u0."inserted_at", u0."updated_at" FROM "users" AS u0 []
[info] Sent 200 in 40ms
[error] Handler {OpentelemetryPhoenix, :endpoint_stop} has failed and has been detached. Class=:error
Reason=:undef
Stacktrace=[
  {OpentelemetryTelemetry, :set_current_telemetry_span,
   [
     :opentelemetry_phoenix,
     %{
       conn: %Plug.Conn{
         adapter: {Plug.Cowboy.Conn, :...},
         assigns: %{layout: false, users: []},
         before_send: [#Function<0.11227428/1 in Plug.Telemetry.call/2>],
         body_params: %{},
         cookies: %{},
         halted: false,
         host: "localhost",
         method: "GET",
         owner: #PID<0.523.0>,
         params: %{},
         path_info: ["api", "users"],
         path_params: %{},
         port: 4000,
         private: %{
           MyTelemetryApiWeb.Router => {[], %{}},
           :phoenix_action => :index,
           :phoenix_controller => MyTelemetryApiWeb.UserController,
           :phoenix_endpoint => MyTelemetryApiWeb.Endpoint,
           :phoenix_format => "json",
           :phoenix_layout => {MyTelemetryApiWeb.LayoutView, :app},
           :phoenix_request_logger => {"request_logger", "request_logger"},
           :phoenix_router => MyTelemetryApiWeb.Router,
           :phoenix_template => "index.json",
           :phoenix_view => MyTelemetryApiWeb.UserView,
           :plug_session_fetch => #Function<1.123471702/1 in Plug.Session.fetch_session/1>
         },
         query_params: %{},
         query_string: "",
         remote_ip: {127, 0, 0, 1},
         req_cookies: %{},
         req_headers: [
           {"accept", "*/*"},
           {"host", "localhost:4000"},
           {"user-agent", "curl/7.68.0"}
         ],
         request_path: "/api/users",
         resp_body: ["{\"", [[] | "data"], "\":", "[]", 125],
         resp_cookies: %{},
         resp_headers: [
           {"content-type", "application/json; charset=utf-8"},
           {"cache-control", "max-age=0, private, must-revalidate"},
           {"x-request-id", "FnfT5pqxgPFA0UMAAANj"}
         ],
         scheme: :http,
         script_name: [],
         secret_key_base: :...,
         state: :set,
         status: 200
       },
       options: []
     }
   ], []},
  {OpentelemetryPhoenix, :handle_endpoint_stop, 4,
   [file: 'lib/opentelemetry_phoenix.ex', line: 135]},
  {:telemetry, :"-execute/3-fun-0-", 4,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/telemetry/src/telemetry.erl',
     line: 135
   ]},
  {:lists, :foreach, 2, [file: 'lists.erl', line: 1342]},
  {Plug.Telemetry, :"-call/2-fun-0-", 4,
   [file: 'lib/plug/telemetry.ex', line: 76]},
  {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 2193]},
  {Plug.Conn, :run_before_send, 2, [file: 'lib/plug/conn.ex', line: 1691]},
  {Plug.Conn, :send_resp, 1, [file: 'lib/plug/conn.ex', line: 407]},
  {MyTelemetryApiWeb.UserController, :action, 2,
   [file: 'lib/my_telemetry_api_web/controllers/user_controller.ex', line: 1]},
  {MyTelemetryApiWeb.UserController, :phoenix_controller_pipeline, 2,
   [file: 'lib/my_telemetry_api_web/controllers/user_controller.ex', line: 1]},
  {Phoenix.Router, :__call__, 2, [file: 'lib/phoenix/router.ex', line: 352]},
  {MyTelemetryApiWeb.Endpoint, :plug_builder_call, 2,
   [file: 'lib/my_telemetry_api_web/endpoint.ex', line: 1]},
  {MyTelemetryApiWeb.Endpoint, :"call (overridable 3)", 2,
   [file: 'lib/plug/debugger.ex', line: 132]},
  {MyTelemetryApiWeb.Endpoint, :call, 2,
   [file: 'lib/my_telemetry_api_web/endpoint.ex', line: 1]},
  {Phoenix.Endpoint.Cowboy2Handler, :init, 4,
   [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 65]},
  {:cowboy_handler, :execute, 2,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/cowboy/src/cowboy_handler.erl',
     line: 37
   ]},
  {:cowboy_stream_h, :execute, 3,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/cowboy/src/cowboy_stream_h.erl',
     line: 300
   ]},
  {:cowboy_stream_h, :request_process, 3,
   [
     file: '/home/ricardoccpaiva/Documents/Projects/ricardoccpaiva/my_telemetry_api/deps/cowboy/src/cowboy_stream_h.erl',
     line: 291
   ]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
]

**Comment by bryannaegele** [comment]
Can you verify you have `v1.0.0-beta.2` in your mix lock for `opentelemetry_telemetry`?

**Comment by ricardoccpaiva** [comment]
> Can you verify you have `v1.0.0-beta.2` in your mix lock for `opentelemetry_telemetry`?

`:opentelemetry_telemetry, "1.0.0-beta.1"`

**Comment by bryannaegele** [comment]
Ah. You'll need to update to beta 2 and let me know if you get any errors. 😃

**Comment by ricardoccpaiva** [comment]
> Ah. You'll need to update to beta 2 and let me know if you get any errors.

then shouldn't the dependency be updated here? :point_down: 
https://github.com/opentelemetry-beam/opentelemetry_phoenix/blob/main/mix.exs#L59

**Comment by bryannaegele** [comment]
> > Ah. You'll need to update to beta 2 and let me know if you get any errors.
> 
> then shouldn't the dependency be updated here? 👇
> https://github.com/opentelemetry-beam/opentelemetry_phoenix/blob/main/mix.exs#L59

The lock file has the correct version. You can just do `mix deps.update opentelemetry_telemetry`.

https://github.com/opentelemetry-beam/opentelemetry_phoenix/blob/main/mix.lock#L17

**Pull request merged**
