### PR TITLE
Update opentelemetry deps to 0.6.0

### PR DESCRIPTION
**Pull request by ricardoccpaiva**
- Update opentelemetry deps to 0.6.0
- Fix 2 compile warnings

### CODE REVIEW

**Comment by bryannaegele** [comment]
Hey, Ricardo. Did you validate against the Otel spec that no other changes are required for 0.6.0 updates? The way I usually do it is by doing diffs in the Otel spec repo between the version you're updating from to the one you're updating to, so tags 0.5.0 -> 0.6.0

**Comment by ricardoccpaiva** [comment]
> Hey, Ricardo. Did you validate against the Otel spec that no other changes are required for 0.6.0 updates? The way I usually do it is by doing diffs in the Otel spec repo between the version you're updating from to the one you're updating to, so tags 0.5.0 -> 0.6.0

From my short experience with Otel and looking [at this changelog](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md#v060-2020-07-01), it seems that nothing is going to be not compliant with the spec but.... for some reason the exporting is failing after upgrading `opentelemetry` and `opentelemetry_api` to `v0.6.0` :point_down: 

**This happens when some exception is raised**, i tried with a invalid query param, for instance, a string when the controller is expecting a number.
````elixir 
[info] exporter threw exception: exporter=:opentelemetry_exporter :error::function_clause stacktrace=[
  {:opentelemetry_exporter, :to_otlp_status, [:Error],
   [
     file: '/my_telemetry_api/deps/opentelemetry_exporter/src/opentelemetry_exporter.erl',
     line: 254
   ]},
```` 

I noticed this [new field](https://github.com/open-telemetry/opentelemetry-specification/pull/641), I will try to open a PR with this new field.

**Comment by ricardoccpaiva** [comment]
@bryannaegele did you see my last comment? Any thoughts or ideas?
I Will try to debug this... not sure exactly how :thinking:

**Comment by bryannaegele** [comment]
That field isn't a required field. Looking at your error, something is failing in the exporter. Looking at that, this has to do with the changes in the spec to the status code being set.

Looking at it briefly, I think https://github.com/opentelemetry-beam/opentelemetry_phoenix/blob/main/lib/opentelemetry_phoenix.ex#L166 needs to have the atom be lowercased to `:error`.

As a heads up, there is a larger issue which was discovered by Gustavo around span contexts that happened in v0.5 which I need to look into this week, so a new version may not get to hex right away.

**Comment by ricardoccpaiva** [comment]
> That field isn't a required field.

I know, but we can add it anyway.

> Looking at it briefly, I think https://github.com/opentelemetry-beam/opentelemetry_phoenix/blob/main/lib/opentelemetry_phoenix.ex#L166 needs to have the atom be lowercased to :error.

I'll try that to see if it fixes the error.

Thanks for your reply, ping me back when you have some news.

**Comment by bryannaegele** [comment]
Closing in favor of #23. We're going to go straight to 1.0.0-rc

**Pull request closed without merging**
